Repository Oplaner/Wspollokator, pull requests merged in 2021-12, with the labels that each got.

#37 Issue 35 Completed
  Wspollokator.xcodeproj/project.pbxproj
  Wspollokator/Models/Conversation.swift
  Wspollokator/Models/User.swift
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/Avatar.swift
  Wspollokator/Views/Conversations/ConversationView.swift
  Wspollokator/Views/Conversations/ConversationsList.swift
  Wspollokator/Views/Conversations/NewConversation.swift
  Wspollokator/Views/Profiles/DescriptionChange.swift
  Wspollokator/Views/Profiles/UserProfile.swift
  Wspollokator/Views/SavedList.swift
  Wspollokator/Views/Search/ListMapSearchView.swift
  Wspollokator/Views/Search/SearchedList.swift
Labels: UI, Komunikacja

#40 Issue 39 Completed
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/ContentView.swift
  Wspollokator/Views/Profiles/DescriptionChange.swift
  Wspollokator/Views/Profiles/MyProfile.swift
  Wspollokator/Views/Profiles/PasswordChange.swift
  Wspollokator/Views/Profiles/Settings.swift
  Wspollokator/Views/Unauthorized Access/Login.swift
  Wspollokator/Views/Unauthorized Access/SignUp.swift
Labels: UI, Komunikacja

#41 Issue 38 Completed
  Wspollokator.xcodeproj/project.pbxproj
  Wspollokator/Helpers/ImagePicker.swift
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/Avatar.swift
  Wspollokator/Views/Profiles/PasswordChange.swift
  Wspollokator/Views/Profiles/Settings.swift
Labels: UI, Komunikacja

#42 Revert "Issue 38 Completed"
  Wspollokator.xcodeproj/project.pbxproj
  Wspollokator/Helpers/ImagePicker.swift
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/Avatar.swift
  Wspollokator/Views/Profiles/PasswordChange.swift
  Wspollokator/Views/Profiles/Settings.swift
Labels: UI, Komunikacja

#43 Issue 38 Completed
  Wspollokator.xcodeproj/project.pbxproj
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/Avatar.swift
  Wspollokator/Views/Profiles/ImagePicker.swift
  Wspollokator/Views/Profiles/Settings.swift
  Wspollokator/Views/Profiles/UserProfile.swift
Labels: UI, Komunikacja

#44 Restored Missing ImagePicker
  Wspollokator.xcodeproj/project.pbxproj
Labels: Organizacja

#45 All Missing Things Restored and Changed Resizing
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/Avatar.swift
Labels: UI, Organizacja

#46 Issues 28 29
  Wspollokator.xcodeproj/project.pbxproj
  Wspollokator.xcodeproj/project.xcworkspace/xcuserdata/szymontamborski.xcuserdatad/UserInterfaceState.xcuserstate
  Wspollokator.xcodeproj/xcuserdata/szymontamborski.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Wspollokator.xcodeproj/xcuserdata/szymontamborski.xcuserdatad/xcschemes/xcschememanagement.plist
  Wspollokator/Views/Maps/LocationManager.swift
  Wspollokator/Views/Maps/MapView.swift
  Wspollokator/Views/Maps/MapViewContainer.swift
  Wspollokator/Views/Maps/MapViewRepresentable.swift
  Wspollokator/Views/Profiles/MyProfile.swift
  Wspollokator/Views/Search/ListMapSearchView.swift
Labels: UI, Komunikacja

#48 Issue 47 Completed
  Wspollokator.xcodeproj/project.pbxproj
  Wspollokator/Helpers/CoordinateExtension.swift
  Wspollokator/Helpers/GlobalHelpers.swift
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/Maps/LocationManager.swift
  Wspollokator/Views/Maps/MapDetails.swift
  Wspollokator/Views/Maps/MapView.swift
  Wspollokator/Views/Maps/MapViewContainer.swift
  Wspollokator/Views/Maps/MapViewRepresentable.swift
  Wspollokator/Views/Maps/UserAnnotation.swift
  Wspollokator/Views/Profiles/DescriptionChange.swift
  Wspollokator/Views/Profiles/MyProfile.swift
  Wspollokator/Views/Search/ListMapSearchView.swift
  Wspollokator/Views/Search/SearchedList.swift
Labels: UI, Komunikacja

#52 UI Updates & Full Concurrent Saving
  Wspollokator.xcodeproj/project.pbxproj
  Wspollokator/Assets.xcassets/AppIcon.appiconset/app-store.png
  Wspollokator/Assets.xcassets/AppIcon.appiconset/iphone-app@2x.png
  Wspollokator/Assets.xcassets/AppIcon.appiconset/iphone-app@3x.png
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/ContentView.swift
  Wspollokator/Views/Conversations/ChatRow.swift
  Wspollokator/Views/Conversations/ConversationsList.swift
  Wspollokator/Views/Conversations/NewConversation.swift
  Wspollokator/Views/Filters/FilterView.swift
  Wspollokator/Views/Filters/FilterViewContainer.swift
  Wspollokator/Views/ListRow.swift
  Wspollokator/Views/Maps/MapView.swift
  Wspollokator/Views/Maps/MapViewContainer.swift
  Wspollokator/Views/Maps/MapViewRepresentable.swift
  Wspollokator/Views/Maps/UserAnnotation.swift
  Wspollokator/Views/Profiles/MyProfile.swift
  Wspollokator/Views/Profiles/UserProfile.swift
  Wspollokator/Views/SavedList.swift
  Wspollokator/Views/Search/ListMapSearchView.swift
  Wspollokator/WspollokatorApp.swift
Labels: UI, Komunikacja

#53 Fixed Reset to User Preferences Button in FilterViewContainer
  Wspollokator/Views/Filters/FilterRow.swift
  Wspollokator/Views/Filters/FilterView.swift
  Wspollokator/Views/Filters/FilterViewContainer.swift
Labels: UI

#54 Issue 51 Completed
  Wspollokator.xcodeproj/project.pbxproj
  Wspollokator/Models/Rating.swift
  Wspollokator/Models/User.swift
  Wspollokator/ViewModel/Networking.swift
  Wspollokator/ViewModel/ViewModel.swift
  Wspollokator/Views/Conversations/ConversationView.swift
  Wspollokator/Views/Conversations/ConversationsList.swift
  Wspollokator/Views/Profiles/DescriptionChange.swift
  Wspollokator/Views/Profiles/MyProfile.swift
  Wspollokator/Views/Profiles/PasswordChange.swift
  Wspollokator/Views/Profiles/Settings.swift
  Wspollokator/Views/Profiles/UserProfile.swift
  Wspollokator/Views/Ratings/NewRating.swift
  Wspollokator/Views/Ratings/RatingList.swift
  Wspollokator/Views/Ratings/RatingStars.swift
  Wspollokator/Views/Ratings/RatingView.swift
  Wspollokator/Views/Search/ListMapSearchView.swift
Labels: UI, Model, Komunikacja
